version: '3'

services:

  poke-api:
    image : sosismayo/fp-b201:poke-api
    container_name : poke-api
    ports :
      - "3000:3000"
    restart : unless-stopped
  reverse-proxy:
    container_name : reverse-proxy
    ports : 
      - "443:443"
    image: sosismayo/fp-b201:reverse-proxy
    restart : unless-stopped
    volumes : 
      - ./nginx/ssl/example.crt:/etc/nginx/ssl/example.crt
      - ./nginx/ssl/example.key:/etc/nginx/ssl/example.key
